export const RELATIONSHIP_PATHS = [
  {
    id: "cash_options",
    name: "Cash and liquidity choices",
    family: "Cash",
    description: "Compare access, settlement, and the characteristics of available cash choices.",
    sourceUrl: "https://www.schwab.com/cash-investments",
  },
  {
    id: "rollover_support",
    name: "Rollover specialist",
    family: "Retirement",
    description: "Review former-plan choices and the correct rollover process before moving assets.",
    sourceUrl: "https://www.schwab.com/ira/rollover-ira",
  },
  {
    id: "automated_investing",
    name: "Schwab Intelligent Portfolios",
    family: "Automated investing",
    description: "Explore a diversified portfolio that is monitored and rebalanced automatically.",
    sourceUrl: "https://www.schwab.com/intelligent-portfolios",
  },
  {
    id: "managed_portfolios",
    name: "Schwab Managed Portfolios",
    family: "Professional management",
    description: "Compare professionally managed portfolios of funds or ETFs with automated investing.",
    sourceUrl: "https://www.schwab.com/managed-portfolios",
  },
  {
    id: "wealth_advisory",
    name: "Schwab Wealth Advisory",
    family: "Personal advice",
    description: "Explore a dedicated advisory relationship for broader financial planning needs.",
    sourceUrl: "https://www.schwab.com/wealth-management/wealth-advisor",
  },
  {
    id: "financial_consultant",
    name: "Financial Consultant conversation",
    family: "Personal advice",
    description: "Explore a relationship conversation that connects the client's goals and Schwab accounts.",
    sourceUrl: "https://www.schwab.com/wealth-management/wealth-advisor",
  },
  {
    id: "advisor_network",
    name: "Schwab Advisor Network",
    family: "Independent advice",
    description: "Explore a referral to a prescreened independent advisor for broader advice needs.",
    sourceUrl: "https://www.schwab.com/advisor-network",
  },
  {
    id: "tax_aware_review",
    name: "Tax-aware investing review",
    family: "Tax considerations",
    description: "Review existing holdings, potential sale consequences, and available tax-aware approaches with a specialist.",
    sourceUrl: "https://www.schwab.com/invest-with-us/tax-efficient-investing",
  },
  {
    id: "retirement_income",
    name: "Retirement income planning",
    family: "Retirement",
    description: "Explore withdrawal planning and goal tracking while keeping RMD servicing separate.",
    sourceUrl: "https://www.schwab.com/automated-investing/goal-tracker",
  },
  {
    id: "schwab_plan",
    name: "Schwab Plan",
    family: "Financial planning",
    description: "Bring retirement goals and outside assets into a complimentary planning conversation.",
    sourceUrl: "https://www.schwab.com/financial-planning/schwab-plan",
  },
  {
    id: "personalized_indexing",
    name: "Schwab Personalized Indexing",
    family: "Tax-aware management",
    description: "Explore direct indexing, potential exclusions, and tax-aware portfolio management with a specialist.",
    sourceUrl: "https://www.schwab.com/direct-indexing",
  },
  {
    id: "investor_checking",
    name: "Schwab Bank Investor Checking",
    family: "Banking",
    description: "Compare a linked checking account for everyday money movement and travel needs.",
    sourceUrl: "https://www.schwab.com/checking",
  },
  {
    id: "home_lending",
    name: "Home lending conversation",
    family: "Lending",
    description: "Connect a client with a home lending specialist after the immediate wire need is handled.",
    sourceUrl: "https://www.schwab.com/mortgages",
  },
  {
    id: "pledged_asset_line",
    name: "Pledged Asset Line review",
    family: "Lending",
    description: "Compare borrowing against eligible non-retirement assets with selling; discuss costs and collateral risk.",
    sourceUrl: "https://www.schwab.com/pledged-asset-line",
  },
  {
    id: "education_savings",
    name: "Education savings choices",
    family: "Family",
    description: "Compare 529, education savings, and account-control considerations with a specialist.",
    sourceUrl: "https://www.schwab.com/saving-for-college/college-savings-plans",
  },
  {
    id: "college_529",
    name: "Schwab 529 Plan",
    family: "Education",
    description: "Compare education-focused savings with other account structures and family priorities.",
    sourceUrl: "https://www.schwab.com/saving-for-college/college-savings-plans",
  },
  {
    id: "education_savings_account",
    name: "Education Savings Account",
    family: "Education",
    description: "Review whether an ESA's education uses and rules match the family's goals.",
    sourceUrl: "https://www.schwab.com/educational-savings-account",
  },
  {
    id: "custodial_account",
    name: "Schwab One Custodial Account",
    family: "Family",
    description: "Compare flexible gifts to a child with the account-control tradeoffs.",
    sourceUrl: "https://www.schwab.com/custodial-account",
  },
  {
    id: "organization_account",
    name: "Schwab Organization Account",
    family: "Business",
    description: "Explore a business investment account while protecting near-term operating cash.",
    sourceUrl: "https://www.schwab.com/organizational-accounts",
  },
  {
    id: "teen_investor",
    name: "Schwab Teen Investor",
    family: "Family",
    description: "Explore a supervised teen investing account and its permitted features.",
    sourceUrl: "https://www.schwab.com/teen-account",
  },
  {
    id: "trust_services",
    name: "Personal trust services",
    family: "Legacy",
    description: "Discuss professional trust administration roles with the client's estate team.",
    sourceUrl: "https://www.schwab.com/personal-trust-services/services",
  },
  {
    id: "charitable_giving",
    name: "DAFgiving360",
    family: "Giving",
    description: "Compare a donor-advised fund with direct gifts of appreciated securities.",
    sourceUrl: "https://www.dafgiving360.org/non-cash-contribution-options",
  },
  {
    id: "small_business_retirement",
    name: "Small business retirement plans",
    family: "Business",
    description: "Compare SEP, SIMPLE, and 401(k) choices before selecting a plan for an employer with staff.",
    sourceUrl: "https://www.schwab.com/small-business-retirement-plans",
  },
  {
    id: "fractional_shares",
    name: "Fractional shares and education",
    family: "Self-directed",
    description: "Support a small-balance investor who wants to learn and choose investments herself.",
    sourceUrl: "https://www.schwab.com/fractional-shares-stock-slices",
  },
  {
    id: "trading_tools",
    name: "thinkorswim and paperMoney",
    family: "Self-directed",
    description: "Explore trading tools and simulated practice without implying a strategy is safe or suitable.",
    sourceUrl: "https://www.schwab.com/content/thinkorswim-papermoney-stock-trading-simulator",
  },
  {
    id: "service_recovery",
    name: "Service recovery",
    family: "Service",
    description: "Resolve the open problem and document ownership before discussing any further relationship.",
    sourceUrl: "https://www.schwab.com/contact-us",
  },
  {
    id: "inherited_ira_support",
    name: "Inherited IRA specialist",
    family: "Retirement",
    description: "Clarify beneficiary distribution obligations before discussing investment changes.",
    sourceUrl: "https://www.schwab.com/ira/inherited-and-custodial-ira",
  },
] as const;

export type RelationshipPathId = (typeof RELATIONSHIP_PATHS)[number]["id"];
